SalesWebProject/Models/SalesRecord.cs
using SalesWebProject.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesWebProject.Models
{
    [Table("SalesRecord")]
    public class SalesRecord
    {
        [Key]
        public int Id { get; set; }

        public DateTime Date { get; set; }

        public double Amount { get; set; }

        public SaleStatusEnum Status { get; set; }

        [ForeignKey("Seller")]
        public int SellerId { get; set; }

        public virtual Seller Seller { get; set; }
    }
}

SalesWebProject/ViewModels/SalesRecord.cs
using SalesWebProject.Enums;
using SalesWebProject.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesWebProject.ViewModels
{
    public class SalesRecordViewModel
    {
        public int Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Date { get; set; }

        public double Amount { get; set; }

        public SaleStatusEnum Status { get; set; }

        public int SellerId { get; set; }

        public Seller Seller { get; set; }
    }
}

SalesWebProject/ViewModels/SalesRecordsViewModel.cs
using SalesWebProject.Enums;
using SalesWebProject.Models;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesWebProject.ViewModels
{
    public class SalesRecordsMainViewModel
    {
        public SalesRecordsMainViewModel()
        {
            Filter = new SalesRecordFilter();
        }

        public List<SalesRecordsGroupedViewModel> SalesRecordsGroups { get; set; }
        public SalesRecordFilter Filter { get; set; }
    }

    public class SalesRecordsGroupedViewModel
    {
        public string Name { get; set; }

        public int Counter { get; set; }

        public List<SalesRecordsViewModel> SalesRecords { get; set; }
    }

    public class SalesRecordsViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Campo {0} requerido")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public string DateString { get { return Date.ToShortDateString(); } }

        [Required(ErrorMessage = "Campo {0} requerido")]
        public double Amount { get; set; }

        public SaleStatusEnum Status { get; set; }

        public string DepartmentName { get; set; }

        [Display(Name = "Vendedor")]
        [Required(ErrorMessage = "Campo de vendedor requerido")]
        public int SellerId { get; set; }

        public string SellerName { get; set; }

        public Seller Seller { get; set; }
    }

    public class SalesRecordFilter
    {
        public SalesRecordFilter()
        {
            DateEnd = DateTime.Now;
            DateStart = DateTime.Now.AddYears(-5);
            Status = SalesRecordsGroupType.Department;
        }

        public string Name { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}")]
        public DateTime? DateStart { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}")]

        public DateTime? DateEnd { get; set; }

        public SalesRecordsGroupType Status { get; set; }

        public bool AllPeriods { get; set; }
    }

    public enum SalesRecordsGroupType
    {
        [Description("Departamento")]
        Department = 1,

        [Description("Status da Venda")]
        Status = 2,

        [Description("Vendedor")]
        Seller = 3
    }
}

SalesWebProject/Controllers/SalesRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalesWebProject.Models;
using SalesWebProject.ViewModels;

namespace SalesWebProject.Controllers
{
    public class SalesRecordController : Controller
    {
        private SalesContext _context;

        public SalesRecordController(SalesContext context)
        {
            this._context = context;
        }

        public ActionResult Index()
        {
            List<SalesRecordViewModel> list = (from m in _context.SalesRecord
                                              select new SalesRecordViewModel
                                              {
                                                  Id = m.Id,
                                                  Date = m.Date,
                                                  Amount = m.Amount,
                                                  Status = m.Status,    
                                                  SellerId = m.SellerId,    
                                                  
                                              }).ToList();

            return View(list);
        }

        public ActionResult Details(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = _context.Departments.FirstOrDefault(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View();
        }

        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Create(Department department)
        {
            if (department.Name.Count() < 2)
            {
                throw new Exception("Nome Inválido");
            }
            _context.Add(department);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var department = _context.Departments.FirstOrDefault(m => m.Id == id);
            if (department == null)
            {
                throw new Exception("Departamento não encontrado");
            }

            var item = new DepartmentViewModel
            {
                Id = department.Id,
                Name = department.Name,
            };

            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(DepartmentViewModel viewModel)
        {
            var department = _context.Departments.FirstOrDefault(m => m.Id == viewModel.Id);
            if (department == null)
            {
                throw new Exception("Departamento não encontrado");
            }

            department.Name = viewModel.Name;

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            var department = _context.Departments.FirstOrDefault(m => m.Id == id);
            if (department == null)
            {
                throw new Exception("Departamento não encontrado");
            }

            var item = new DepartmentViewModel
            {
                Id = department.Id,
                Name = department.Name,
            };

            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {
                return Problem();
            }
            var department = _context.Departments.Find(id);
            if (department != null)
            {
                _context.Departments.Remove(department);
            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(i => i.Id == id);
        }
    }
}

SalesWebProject/Controllers/SalesRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalesWebProject.Models;
using SalesWebProject.ViewModels;
using System.Diagnostics;
using Mysqlx;
using SalesWebProject.Enums;
using SalesWebProject.Helpers;

namespace SalesWebProject.Controllers
{
    public class SalesRecordsController : Controller
    {
        private readonly SalesContext _context;
        public SalesRecordsController(SalesContext context)
        {
            _context = context;
        }

        public ActionResult Index(SalesRecordsMainViewModel viewModel)
        {

            SalesRecordsGroupType status = viewModel.Filter.Status;

            var tmpQuery = from m in _context.SalesRecord.AsNoTracking()
                           select new
                           {
                               m.Id,
                               m.Date,
                               m.Amount,
                               m.Status,
                               Seller = new
                               {
                                   Id = m.Seller.Id,
                                   m.Seller.Name,
                                   m.Seller.DepartmentId,
                                   DepartmentName = m.Seller.Department.Name

                               },
                           };

            if (!string.IsNullOrWhiteSpace(viewModel.Filter.Name))
            {
                tmpQuery = tmpQuery.Where(m => m.Seller.Name.Contains(viewModel.Filter.Name));
            }

            if (!viewModel.Filter.AllPeriods)
            {
                if (viewModel.Filter.DateStart != null)
                {
                    tmpQuery = tmpQuery.Where(m => m.Date >= viewModel.Filter.DateStart);
                }

                if (viewModel.Filter.DateEnd != null)
                {
                    tmpQuery = tmpQuery.Where(m => m.Date <= viewModel.Filter.DateEnd);
                }
            }

            var salesRecords = new SalesRecordsMainViewModel
            {

                SalesRecordsGroups = (from m in tmpQuery.ToList()
                                      group m by

                                      status == SalesRecordsGroupType.Department ?
                                      new { Id = m.Seller.DepartmentId, Name = m.Seller.DepartmentName } :
                                      status == SalesRecordsGroupType.Status ?
                                      new { Id = (int)m.Status, Name = m.Status.ToString() } :
                                      new { Id = m.Seller.Id, Name = m.Seller.Name }
                                      into g

                                      select new SalesRecordsGroupedViewModel
                                      {
                                          Name = status == SalesRecordsGroupType.Status ?
                                          ((SaleStatusEnum)Enum.Parse(typeof(SaleStatusEnum), g.Key.Name)).GetDescription() :
                                          g.Key.Name,

                                          Counter = g.Count(m => status == SalesRecordsGroupType.Department ?
                                          m.Seller.DepartmentId == g.Key.Id :
                                          status == SalesRecordsGroupType.Status ?
                                          (int)m.Status == g.Key.Id :
                                          m.Seller.Id == g.Key.Id),

                                          SalesRecords = (from m in g.ToList()
                                                          orderby m.Seller.Name
                                                          select new SalesRecordsViewModel
                                                          {
                                                              Id = m.Id,
                                                              Date = m.Date,
                                                              Amount = m.Amount,
                                                              Status = m.Status,
                                                              SellerName = m.Seller.Name,
                                                              DepartmentName = m.Seller.DepartmentName
                                                          }).ToList()
                                      }).ToList(),

                Filter = viewModel.Filter
            };

            return View(salesRecords);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var sellers = SellersController.ListAll(_context, true);
            ViewBag.Sellers = new SelectList(sellers, "Value", "Text");
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SalesRecordsViewModel viewModel)
        {
            if (viewModel.SellerId == 0)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor inválido" });
            }

            var saleRecord = new SalesRecord
            {
                Date = viewModel.Date,
                Amount = viewModel.Amount,
                Status = SaleStatusEnum.Pending,
                SellerId = viewModel.SellerId,
            };

            _context.SalesRecord.Add(saleRecord);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var saleRecord = _context.SalesRecord.FirstOrDefault(m => m.Id == id);
            if (saleRecord == null)
            {
                throw new Exception("Departamento não encontrado");
            }

            var viewModel = new SalesRecordsViewModel
            {
                Id = saleRecord.Id,
                Date = saleRecord.Date,
                Amount = saleRecord.Amount,
                Status = saleRecord.Status,
                SellerId = saleRecord.SellerId,
            };

            var enums = EnumHelpers.GenerateSelectList<SaleStatusEnum>();
            ViewBag.Status = new SelectList(enums, "Value", "Text");

            var sellers = SellersController.ListAll(_context, true);
            ViewBag.Sellers = new SelectList(sellers, "Value", "Text");

            return View(viewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SalesRecordsViewModel viewModel)
        {
            var saleRecord = _context.SalesRecord.FirstOrDefault(m => m.Id == viewModel.Id);

            if (saleRecord == null)
            {
                throw new Exception("Venda não encontrada");
            }

            saleRecord.Date = viewModel.Date;
            saleRecord.Amount = viewModel.Amount;
            saleRecord.Status = viewModel.Status;
            saleRecord.SellerId = viewModel.SellerId;


            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var saleRecord = _context.SalesRecord.Include(m => m.Seller).FirstOrDefault(m => m.Id == id);
            if (saleRecord == null)
            {
                throw new Exception("Venda não encontrada");
            }

            var viewModel = new SalesRecordsViewModel
            {
                Id = saleRecord.Id,
                Date = saleRecord.Date,
                Status = saleRecord.Status,
                Amount = saleRecord.Amount,
                SellerName = saleRecord.Seller.Name,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SalesRecordsViewModel viewModel)
        {
            try
            {
                var saleRecord = _context.SalesRecord.FirstOrDefault(m => m.Id == viewModel.Id);
                if (saleRecord == null)
                {
                    throw new Exception("Vendedor não encontrado");
                }
                _context.SalesRecord.Remove(saleRecord);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Error), new { message = "Não foi possível deletar este item em razão de chaves primárias no banco de dados" });
            }
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(i => i.Id == id);
        }
    }
}

SalesWebProject/Views/SalesRecords/Create.cshtml
@model SalesWebProject.ViewModels.SalesRecordsViewModel

@{
    ViewBag.Title = "Cadastrar nova venda";
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <hr style="margin-bottom: 0.5rem" />

    <div class="row">
        <div class="col-md-4">
            <form asp-controller="SalesRecords" asp-action="Create">
                <div class="form-group">
                    <label asp-for="@Model.Date" class="control-label">Data</label>
                    <input asp-for="@Model.Date" class="form-control" placeholder="Data" />
                    <span asp-validation-for="@Model.Date" class="text-danger"></span>
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Amount" class="control-label">Valor do Produto</label>
                    <input asp-for="@Model.Amount" class="form-control" placeholder="Valor" />
                    <span asp-validation-for="@Model.Amount" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.SellerId" class="control-label">Vendedor</label>
                    <select asp-for="@Model.SellerId" asp-items="@ViewBag.Sellers" class="form-control"></select>
                </div>

                <div class="d-flex justify-content-between align-items-center form-group mt-4">
                    <a asp-action="Index" class="btn btn-outline-primary" style="font-size: 1.2rem">Retornar</a>
                    <button type="submit" class="btn btn-outline-primary" style="font-size: 1.2rem">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesWebProject/Views/SalesRecords/Delete.cshtml
@model SalesWebProject.ViewModels.SalesRecordsViewModel
@using System.Globalization;

@{
    ViewBag.Title = string.Format("Confimar exclusão da Venda #{0}", Model.Id);
}}

<div class="container">
    <h4>@ViewBag.Title</h4>

    <hr style="margin-bottom: 0.5rem" />

    <div class="row">
        <div class="col-md-6">
            <form asp-controller="SalesRecords" asp-action="Delete">
                @Html.HiddenFor(m => m.Id)

                <div class="form-group">
                    <label asp-for="@Model.Date" class="control-label">Data</label>
                    <input readonly asp-for="@Model.Date" class="form-control" placeholder="Data" />
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Amount" class="control-label">Quantidade</label>
                    <input readonly asp-for="@Model.Amount" class="form-control" placeholder="Quantidade" />
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Status" class="control-label">Status do Pedido</label>
                    <input readonly asp-for="@Model.Status" value="@Model.Status" class="form-control" placeholder="Status do Pedido" />
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.SellerName" class="control-label">Vendedor</label>
                    <input readonly asp-for="@Model.SellerName" class="form-control" placeholder="Vendedor" />
                </div>

                <div class="d-flex justify-content-between align-items-center form-group mt-4">
                    <a asp-action="Index" class="btn btn-outline-primary" style="font-size: 1.2rem">Voltar</a>
                    <button type="submit" class="btn btn-outline-primary" style="font-size: 1.2rem">Excluir</button>
                </div>
            </form>
        </div>
    </div>
</div>

SalesWebProject/Views/SalesRecords/Details.cshtml
@model SalesWebProject.ViewModels.SalesRecordsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SalesRecord</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Seller.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Seller.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SalesWebProject/Views/SalesRecords/Edit.cshtml
@model SalesWebProject.ViewModels.SalesRecordsViewModel

@{
    ViewBag.Title = string.Format("Editar dados da Venda #(0)", Model.Id);
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <hr style="margin-bottom: 0.5rem" />

    <div class="row">
        <div class="col-md-6">
            <form asp-controller="SalesRecords" asp-action="Edit">
                <div class="form-group">
                    <label asp-for="@Model.Date" class="control-label">Data de Venda</label>
                    <input asp-for="@Model.Date" class="form-control" />
                    <span asp-validation-for="@Model.Date" class="text-danger"></span>
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Amount" class="control-label"></label>
                    <input asp-for="@Model.Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Status" class="control-label">Status do Pedido</label>
                    <select asp-for="@Model.Status" asp-items="@ViewBag.Status" class="form-control"></select>
                    <span asp-validation-for="@Model.Status" class="text-danger"></span>
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.SellerId" class="control-label"></label>
                    <select asp-for="@Model.SellerId" asp-items="@ViewBag.Sellers" class="form-control"></select>
                    <span asp-validation-for="@Model.SellerId" class="text-danger"></span>
                </div>
                <div class="d-flex justify-content-between align-items-center form-group mt-4">
                    <a type="button" asp-action="Index" class="btn btn-outline-primary" style="font-size: 1.2rem">Voltar</a>
                    <button type="submit" class="btn btn-outline-primary" style="font-size: 1.2rem">Salvar</button>
                </div>
            </form>
        </div>
    </div>

</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

SalesWebProject/Views/SalesRecords/Index.cshtml
@model SalesWebProject.ViewModels.SalesRecordsMainViewModel;
@using SalesWebProject.Helpers;
@using System.Globalization;
@using SalesWebProject.ViewModels;

@{
    ViewBag.Title = "Vendas";
}

<div class="container-fluid-content">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h2>@ViewBag.Title</h2>
        </div>
        <div>
            <a asp-controller="SalesRecords" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-lg"></i>
                Novo
            </a>
        </div>
    </div>

    <div class="d-lg-flex mt-2">
        <div class="container-box filter-divisor">
            <form asp-action="Index">
                <div class="form-group">
                    <label asp-for="@Model.Filter.Name" class="control-label">Nome do Vendedor</label>
                    <input asp-for="@Model.Filter.Name" class="form-control" />
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Filter.DateStart" class="control-label">Data de Início</label>
                    <input asp-for="@Model.Filter.DateStart" class="form-control" />
                </div>

                <div class="form-group mt-4">
                    <label asp-for="@Model.Filter.DateEnd" class="control-label">Data Final</label>
                    <input asp-for="@Model.Filter.DateEnd" class="form-control" />
                </div>

                <div class="form-group mt-4">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="@Model.Filter.AllPeriods" value="false" />
                        <label class="form-check-label" asp-for="@Model.Filter.AllPeriods">
                            Usar data para filtragem
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="@Model.Filter.AllPeriods" value="true" />
                        <label class="form-check-label" asp-for="@Model.Filter.AllPeriods">
                            Não usar data para filtragem
                        </label>
                    </div>
                </div>

                <div class="form-group mt-4">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="@Model.Filter.Status" value="@SalesRecordsGroupType.Department" />
                        <label class="form-check-label" asp-for="@Model.Filter.Status">
                            Filtrar por Departamento
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="@Model.Filter.Status" value="@SalesRecordsGroupType.Status" />
                        <label class="form-check-label" asp-for="@Model.Filter.Status">
                            Filtrar por Status
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="@Model.Filter.Status" value="@SalesRecordsGroupType.Seller" />
                        <label class="form-check-label" asp-for="@Model.Filter.Status">
                            Filtrar por Vendedor
                        </label>
                    </div>
                </div>

                <hr />
                <div class="d-flex align-right">
                    <button type="submit" class="btn btn-outline-primary mt-2" style="font-size:1.0rem">
                        Filtrar
                    </button>
                </div>
            </form>
        </div>

        <div class="container-box content-divisor">
            @foreach (var group in Model.SalesRecordsGroups)
            {
                <h5>
                    @(Model.Filter.Status == SalesRecordsGroupType.Department ?
                        string.Format("Departamento - {0}", group.Name) :
                        Model.Filter.Status == SalesRecordsGroupType.Status ?
                        string.Format("Status - {0}", group.Name) :
                        string.Format("Vendedor - {0}", group.Name))

                    <small>(@group.Counter)</small>
                </h5>
                <table class="table table-hover">
                    <thead>
                        <tr class="table-active">
                            <th width="1%">#</th>
                            <th>Vendedor</th>
                            <th>Data</th>
                            <th>Valor da Venda</th>
                            <th>Status</th>
                            <th>Departamento</th>
                            <th width="1%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in group.SalesRecords)
                        {
                            <tr>
                                <td>
                                    <strong>@item.Id.ToString("D2")</strong>
                                </td>
                                <td>
                                    @item.SellerName
                                </td>
                                <td>
                                    @item.DateString
                                </td>
                                <td>
                                    @item.Amount.ToString("C", new CultureInfo("pt-Br"))
                                </td>
                                <td>
                                    @item.Status.GetDescription()
                                </td>
                                <td>
                                    @item.DepartmentName
                                </td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <i class="bi bi-three-dots-vertical" style="font-size: 1.2rem" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                                            <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

<style>
    .container-fluid-content {
        display: flex;
        flex-direction: column;
        margin: 0 auto;
        max-width: 80% !important;
    }

    .container-box {
        border-width: 1px;
        border-style: solid;
        border-radius: 4px;
        border-color: #e7e7e7;
        padding: 20px;
    } 

    .align-right {
        flex-direction: row-reverse;
    }

    .dropdown-toggle {
        font-size: 1.4rem;
    }

    .filter-divisor {
        flex-basis: 20%;
        margin-right: 16px;
        height: fit-content
    }

    .content-divisor {
        flex-basis: 80%
    }

    td, th {
        text-align: left !important;
    }

    tbody > tr:nth-of-type(even) > * {
        background-color: rgba(0,0,0,0.05);
        color: #55595c;
    }
</style>