SalesWebProject/Models/Seller.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;

namespace SalesWebProject.Models
{
    [Table("Seller")]
    public class Seller
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public DateTime BirthDate { get; set; }

        public double BaseSalary { get; set; }

        [ForeignKey("Department")]
        public int DepartmentId { get; set; }

        public virtual Department Department { get; set; }

        public virtual ICollection<SalesRecord> Sales { get; set; } = new List<SalesRecord>();
    }
}

SalesWebProject/Controllers/SellerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using SalesWebProject.Models;
using SalesWebProject.Services;
using SalesWebProject.ViewModels;
using System.Diagnostics;

namespace SalesWebProject.Controllers
{
    public class SellerController : Controller
    {
        private SalesContext _context;

        private readonly SellerService _sellerService;

        public SellerController(SalesContext context)
        {
            this._context = context;
            this._sellerService = new SellerService(context);
        }

        public IActionResult Index()
        {
            var list = _sellerService.GetSellers();

            //List<SellerMainViewModel> list = (from m in _context.Sellers
            //                                  group m by new { m.Department.Id, m.Department.Name } into g
            //                                  orderby g.Key.Name
            //                                  select new SellerMainViewModel
            //                                  {
            //                                      Name = g.Key.Name,
            //                                      Counter = g.Count(i => i.DepartmentId == g.Key.Id),
            //                                      Sellers = (from m in g.ToList()
            //                                                 orderby m.Name
            //                                                 select new SellerViewModel
            //                                                 {
            //                                                     Id = m.Id,
            //                                                     Name = m.Name,
            //                                                     Email = m.Email,
            //                                                     BirthDate = m.BirthDate,
            //                                                     BaseSalary = m.BaseSalary,
            //                                                     Department = m.Department
            //                                                 }).ToList()
            //                                  }).ToList();
            //List<SellerMainViewModel> a = list.Skip(2).Take(3).ToList();
            //return View(a);

            return View(list);
        }

        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Identificador #{0} não encontrado", id) });

            }

            var seller = _context.Sellers.Include(m => m.Department).FirstOrDefault(m => m.Id == id);

            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message ="Vendedor não encontrado"});
            }

            var viewModel = new SellerViewModel
            {
                Id = seller.Id,
                Name = seller.Name,
                Email = seller.Email,
                BirthDate = seller.BirthDate,
                BaseSalary = seller.BaseSalary,
                Department = seller.Department,
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var departments = DepartmentsController.ListAll(_context, true);
            ViewBag.Departments = new SelectList(departments, "Value", "Text", departments.FirstOrDefault());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SellerViewModel viewModel)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(item);
            //}
            if (string.IsNullOrWhiteSpace(viewModel.Name))
            {
                return RedirectToAction(nameof(Error), new { message = "Nome não informado" });
            }

            if (string.IsNullOrWhiteSpace(viewModel.Email))
            {
                return RedirectToAction(nameof(Error), new { message = "E-mail não informado" });

            }

            var seller = new Seller
            {
                Name = viewModel.Name,
                Email = viewModel.Email,
                BirthDate = viewModel.BirthDate,
                BaseSalary = viewModel.BaseSalary,
                DepartmentId = viewModel.DepartmentId,
            };

            _context.Add(seller);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Identificador #{0} não encontrado", id) });

            }

            var seller = _context.Sellers.Include(m => m.Department).FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não fornecido" });
            }

            var item = new SellerViewModel
            {
                Id = seller.Id,
                Name = seller.Name,
                Email = seller.Email,
                BirthDate = seller.BirthDate,
                BaseSalary = seller.BaseSalary,
                DepartmentId = seller.DepartmentId,
            };

            var departments = DepartmentsController.ListAll(_context, true);
            ViewBag.Departments = new SelectList(departments, "Value", "Text", departments.FirstOrDefault());

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SellerViewModel viewModel)
        {
            var seller = _context.Sellers.FirstOrDefault(m => m.Id == viewModel.Id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não fornecido" });
            }

            seller.Name = viewModel.Name;
            seller.Email = viewModel.Email;
            seller.BirthDate = viewModel.BirthDate;
            seller.BaseSalary = viewModel.BaseSalary;
            seller.DepartmentId = viewModel.DepartmentId;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Identificador #{0} não encontrado", id) });

            }

            var seller = _context.Sellers.Include(m => m.Department).FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não fornecido" });
            }

            var viewModel = new SellerViewModel
            {
                Id = seller.Id,
                Name = seller.Name,
                Email = seller.Email,
                BaseSalary = seller.BaseSalary,
                Department = seller.Department
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SellerViewModel viewModel)
        {
            var seller = _context.Sellers.FirstOrDefault(m => m.Id == viewModel.Id);
            if (seller != null)
            {
                _context.Sellers.Remove(seller);
            }

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }
    }
}

SalesWebProject/Controllers/SellersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Mysqlx;
using SalesWebProject.Models;
using SalesWebProject.ViewModels;
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace SalesWebProject.Controllers
{
    public class SellersController : Controller
    {
        private readonly SalesContext _context;
        public SellersController(SalesContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {

            List<SellersMainViewModel> groupedSellers = (from m in _context.Sellers.AsNoTracking()
                                                         group m by new { m.Department.Id, m.Department.Name } into g
                                                         orderby g.Key.Name
                                                         select new SellersMainViewModel
                                                         {
                                                             Name = g.Key.Name,
                                                             Counter = g.Count(i => i.DepartmentId == g.Key.Id),
                                                             SumSalary = g.Sum(i => i.BaseSalary),
                                                             Sellers = (from m in g.ToList()
                                                                        orderby m.Name
                                                                        select new SellersViewModel
                                                                        {
                                                                            Id = m.Id,
                                                                            Name = m.Name,
                                                                            Email = m.Email,
                                                                            BirthDate = m.BirthDate,
                                                                            BaseSalary = m.BaseSalary,
                                                                            Department = m.Department
                                                                        }).ToList()
                                                         }).ToList();
            return View(groupedSellers);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Identificador #{0} não encontrado", id) });

            }

            var seller = _context.Sellers.Include(m => m.Department).FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não encontrado" });
            }

            var sellersView = new SellersViewModel
            {
                Id = seller.Id,
                Name = seller.Name,
                Email = seller.Email,
                BirthDate = seller.BirthDate,
                BaseSalary = seller.BaseSalary,
                Department = seller.Department,
            };

            return View(sellersView);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var departments = DepartmentsController.ListAll(_context, true);
            ViewBag.Departments = new SelectList(departments, "Value", "Text", departments.FirstOrDefault());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SellersViewModel viewModel)
        {

            var seller = new Seller
            {
                Name = viewModel.Name,
                Email = viewModel.Email,
                BirthDate = viewModel.BirthDate,
                BaseSalary = viewModel.BaseSalary,
                DepartmentId = viewModel.DepartmentId,
            };

            _context.Add(seller);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Identificador #{0} não encontrado", id) });

            }

            var seller = _context.Sellers.Include(m => m.Department).FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não fornecido" });
            }

            var item = new SellersViewModel
            {
                Id = seller.Id,
                Name = seller.Name,
                Email = seller.Email,
                BirthDate = seller.BirthDate,
                BaseSalary = seller.BaseSalary,
                DepartmentId = seller.DepartmentId,
            };

            var departments = DepartmentsController.ListAll(_context, true);
            ViewBag.Departments = new SelectList(departments, "Value", "Text", departments.FirstOrDefault());

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SellersViewModel viewModel)
        {
            var seller = _context.Sellers.FirstOrDefault(m => m.Id == viewModel.Id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não fornecido" });
            }

            seller.Name = viewModel.Name;
            seller.Email = viewModel.Email;
            seller.BirthDate = viewModel.BirthDate;
            seller.BaseSalary = viewModel.BaseSalary;
            seller.DepartmentId = viewModel.DepartmentId;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Identificador #{0} não encontrado", id) });

            }

            var seller = _context.Sellers.Include(m => m.Department).FirstOrDefault(m => m.Id == id);
            if (seller == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Vendedor não fornecido" });
            }

            var viewModel = new SellersViewModel
            {
                Id = seller.Id,
                Name = seller.Name,
                Email = seller.Email,
                BaseSalary = seller.BaseSalary,
                Department = seller.Department
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SellersViewModel viewModel)
        {
            try
            {
                var seller = _context.Sellers.FirstOrDefault(m => m.Id == viewModel.Id);
                if (seller == null)
                {
                    throw new Exception("Vendedor não encontrado");
                }

                _context.Sellers.Remove(seller);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Error), new { message = string.Format("Não foi possível deletar este item em razão de chaves primárias no banco de dados") });
            }
        }

        public static List<SelectListItem> ListAll(SalesContext context, bool addEmpty)
        {
            var departments = (from m in context.Sellers
                               select new SelectListItem
                               {
                                   Text = m.Name,
                                   Value = m.Id.ToString()
                               }).ToList();
            if (addEmpty)
            {
                departments.Insert(0, new SelectListItem
                {
                    Text = "Selecione",
                    Value = "0"
                });
            }
            return departments;
        }

    }
}

SalesWebProject/Views/Sellers/Create.cshtml
@model SalesWebProject.ViewModels.SellersViewModel;

@{
    ViewBag.Title = "Cadastro de novo vendedor";
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <hr style="margin-bottom: 0.5rem" />

    <div class="row">
        <div class="col-md-6">
            <form id="information_form" asp-action="Create">
                <div class="form-group">
                    <label asp-for="@Model.DepartmentId" class="control-label">Departamento</label>
                    <select multiple="multiple" asp-for="@Model.DepartmentId" asp-items="@ViewBag.Departments" class="form-select"></select>
                    <div class="form-check mt-2">
                        <input class="form-check-input" type="checkbox" id="checkAllDepartments">
                        <label class="form-check-label" for="checkAllDepartments">
                            Marcar Todos
                        </label>
                    </div>
                    <span class="departament-validation text-danger" style="display:none">Nome de departamento inválido</span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.Email" class="control-label"></label>
                    <input asp-for="@Model.Email" class="form-control" />
                    <span asp-validation-for="@Model.Email" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.BirthDate" class="control-label"></label>
                    <input asp-for="@Model.BirthDate" class="form-control" />
                    <span asp-validation-for="@Model.BirthDate" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.BaseSalary" class="control-label"></label>
                    <input asp-for="@Model.BaseSalary" class="form-control" />
                    <span asp-validation-for="@Model.BaseSalary" class="text-danger"></span>
                </div>
                <div class="d-flex justify-content-between align-items-center form-group mt-4">
                    <a asp-action="Index" class="btn btn-outline-primary" style="font-size: 1.2rem">Retornar</a>
                    <button id="submitButton" type="submit" class="btn btn-outline-primary" style="font-size: 1.2rem">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(function () {
            $(document).on('click', 'button#submitButton', function () {
                var $form = $('form#information_form').first();

                if ($('#DepartmentId option:selected[value="0"]').length == 1) {
                    $('.departament-validation').first().show();
                    return false;
                }
                $form.submit();
            })

            $(document).on('change', 'select#DepartmentId', function () {
                var $this = $(this),
                    $errorMessage = $('.departament-validation');

                if ($this.val() != "0" && ($errorMessage.is(':visible')))
                    $errorMessage.hide();
            })

            $(document).on('change', '#checkAllDepartments', function () {
                var $this = $(this),
                    isChecked = $this.prop('checked') == true,
                    $departmentSelector = $('#DepartmentId'),
                    $selectorOptions = $departmentSelector.find('option');

                $selectorOptions.each(function (_, option) {
                    $option = $(option);
                    if (!$option.val() == "0") {
                        $option.prop('selected', isChecked);
                    }
                });
                console.log($departmentSelector.find('option:selected'));
            })
        })
    </script>
}

SalesWebProject/Views/Sellers/Delete.cshtml
@using System.Globalization;
@model SalesWebProject.ViewModels.SellersViewModel;

@{
    ViewBag.Title = string.Format("Confimar exclusão do Vendedor #{0} - {1}", Model.Id, Model.Name);
}
<div class="container">
    <h4>@ViewBag.Title</h4>

    <hr style="margin-bottom: 0.5rem" />

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Delete">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input readonly asp-for="@Model.Name" class="form-control" />
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.Email" class="control-label"></label>
                    <input readonly asp-for="@Model.Email" class="form-control" />
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.BaseSalary" class="control-label"></label>
                    <input readonly value="@Model.BaseSalary.ToString("C", new CultureInfo("pt-Br"))" class="form-control" />
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.Department" class="control-label"></label>
                    <input readonly asp-for="@Model.Department.Name" class="form-control" />
                </div>
                <div class="d-flex justify-content-between align-items-center form-group mt-4">
                    <a asp-action="Index" class="btn btn-outline-primary" style="font-size: 1.2rem">Voltar</a>
                    <button type="submit" class="btn btn-outline-primary" style="font-size: 1.2rem">Excluir</button>
                </div>
            </form>
        </div>
    </div>
</div>

SalesWebProject/Views/Sellers/Details.cshtml
@model SalesWebProject.ViewModels.SellersViewModel;

@{
    ViewBag.Title = string.Format("Detalhes do(a) vendedor(a) #{0} - {1}", Model.Id, Model.Name);
}

<div class="container">
    <h4>@ViewBag.Title</h4>

    <hr style="margin-bottom: 0.5rem"/>

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label"></label>
                <input readonly asp-for="@Model.Name" class="form-control" />
            </div>
            <div class="form-group mt-4">
                <label asp-for="@Model.Email" class="control-label"></label>
                <input readonly asp-for="@Model.Email" class="form-control" />
            </div>
            <div class="form-group mt-4">
                <label asp-for="@Model.BirthDate" class="control-label"></label>
                <input readonly asp-for="@Model.BirthDateString" class="form-control" />
            </div>
            <div class="form-group mt-4">
                <label asp-for="@Model.BaseSalary" class="control-label"></label>
                <input readonly asp-for="@Model.BaseSalaryMonetary" class="form-control" />
            </div>
            <div class="form-group mt-4">
                <label asp-for="@Model.Department" class="control-label"></label>
                <input readonly asp-for="@Model.Department.Name" class="form-control" />
            </div>
            <div class="d-flex justify-content-between align-items-center form-group mt-4">
                <a class="btn btn-outline-primary" style="font-size: 1.2rem" asp-action="Index">Retornar</a>
                <a class="btn btn-outline-primary" style="font-size: 1.2rem" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
            </div>
        </div>
    </div>
</div>

SalesWebProject/Views/Sellers/Edit.cshtml
@model SalesWebProject.ViewModels.SellersViewModel;

@{
    ViewBag.Title = string.Format("Editar Vendedor #{0} - {1}", Model.Id, Model.Name);
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <hr style="margin-bottom: 0.5rem" />

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div class="form-group">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.Email" class="control-label"></label>
                    <input asp-for="@Model.Email" class="form-control" />
                    <span asp-validation-for="@Model.Email" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.BirthDate" class="control-label"></label>
                    <input asp-for="@Model.BirthDate" class="form-control" />
                    <span asp-validation-for="@Model.BirthDate" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.BaseSalary" class="control-label"></label>
                    <input asp-for="@Model.BaseSalary" class="form-control" />
                    <span asp-validation-for="@Model.BaseSalary" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="@Model.DepartmentId" class="control-label">Departamento</label>
                    <select asp-for="@Model.DepartmentId" asp-items="@ViewBag.Departments" class="form-control"></select>
                </div>
                <div class="d-flex justify-content-between align-items-center form-group mt-4">
                        <a type="button" asp-action="Index" class="btn btn-outline-primary" style="font-size: 1.2rem">Voltar</a>
                        <button type="submit" class="btn btn-outline-primary" style="font-size: 1.2rem">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesWebProject/Views/Sellers/Index.cshtml
@model List<SalesWebProject.ViewModels.SellersMainViewModel>;
@using System.Globalization;

@{
    int counter = 0;
    ViewBag.Title = "Vendedores";
}

<div class="container">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h2>@ViewBag.Title</h2>
        </div>
        <div>
            <a asp-controller="Sellers" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-lg"></i>
                Novo
            </a>
        </div>
    </div>

    <hr style="margin-bottom: 0.5rem" />

    @foreach (var group in Model)
    {
        if (counter != 0)
        {
            <div style="margin-top: 16px;"></div>
        }

        <h6>Depto: @group.Name <small>(@group.Counter)</small></h6>

        <table class="table table-hover">
            <thead>
                <tr class="table-active">
                    <th class="text-left" width="1%">
                        #
                    </th>
                    <th class="text-left" width="25%">
                        Name
                    </th>
                    <th class="text-left" width="25%">
                        E-mail
                    </th>
                    <th class="text-left" width="10%">
                        Data de Nasc.
                    </th>
                    <th class="text-left" width="10%">
                        Salário Base
                        <i class="bi bi-info-circle"
                           data-bs-toggle="tooltip"
                           data-bs-placement="top"
                           data-bs-original-title="Total do Dpto: @group.SumSalary.ToString("C", new CultureInfo("pt-Br"))">
                        </i>
                    </th>
                    <th class="text-left" width="10%">
                        Departamento
                    </th>
                    <th width="1%"></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in group.Sellers)
                {
                    <tr>
                        <td class="text-left">
                            <strong>@item.Id.ToString("D2")</strong>
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Email
                        </td>
                        <td>
                            @item.BirthDateString
                        </td>
                        <td>
                            @item.BaseSalary.ToString("C", new CultureInfo("pt-Br"))
                        </td>
                        <td>
                            @item.Department.Name
                        </td>

                        <td class="text-nowrap">
                            <div class="btn-group" role="group">
                                <i class="bi bi-three-dots-vertical" style="font-size: 1.2rem;" data-bs-toggle="dropdown"></i>
                                <div class="dropdown-menu">
                                    <a asp-action="Details" asp-route-id="@item.Id" class="dropdown-item">Detalhes</a>
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="dropdown-item">Editar</a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="dropdown-item">Deletar</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        counter++;
    }
</div>

@section Scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-bs-toggle="tooltip"]').tooltip();
        });
    </script>
}

<style>
    .text-left {
        text-align: left;
        white-space: nowrap
    }
</style>                                        